version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com

# Por si quieres usar un volumen en el docker
# volumes:
#   postgres-db:
#     external: true
